In [34]:
# Importação de bibliotecas
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [35]:
# Importação da base de dados
df = pd.read_csv('student-mat.csv', sep=';') #Leitura do csv separado por ;
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

In [36]:
# Verificar valores ausentes
df.isnull().sum()

school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
G3            0
dtype: int64

In [37]:
# Total de valores ausentes
df.isnull().sum().sum()

np.int64(0)

In [38]:
# Verificação de valores duplicados
df.duplicated().sum()

np.int64(0)

In [39]:
# Esclusão de valores duplicados
df = df.drop_duplicates()

In [40]:
# Identificação de possíveis outliers

colunas_numericas = df.select_dtypes(include=np.number).columns

for col in colunas_numericas:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    limite_inf = Q1 - (1.5 * IQR)
    limite_sup = Q3 + (1.5 * IQR)

    qtd = ((df[col] < limite_inf) | (df[col] > limite_sup)).sum()

    print(f'{col}: {qtd}')

age: 1
Medu: 0
Fedu: 2
traveltime: 8
studytime: 27
failures: 83
famrel: 26
freetime: 19
goout: 0
Dalc: 18
Walc: 0
health: 0
absences: 15
G1: 0
G2: 13
G3: 0

In [41]:
# Atributos categóricos

# Binários
binarias = [
    'school', 'sex', 'address', 'famsize', 'Pstatus',
    'schoolsup', 'famsup', 'paid', 'activities',
    'nursery', 'higher', 'internet', 'romantic'
]

df_processado = pd.get_dummies(df, columns=binarias, drop_first=True, dtype=int)

# Nominais

nominais = ['Mjob', 'Fjob', 'reason', 'guardian']

label_encoders = {}
# 3. Aplica o Label Encoding coluna por coluna
for coluna in nominais:
    le = LabelEncoder()
    # Ajusta o encoder e transforma a coluna substituindo os valores originais
    df[coluna] = le.fit_transform(df[coluna])
    # Guarda o encoder treinado caso precise decodificar os números mais tarde
    label_encoders[coluna] = le

In [45]:
df.head(10)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,traveltime,studytime,...,Mjob_4,Fjob_1,Fjob_2,Fjob_3,Fjob_4,reason_1,reason_2,reason_3,guardian_1,guardian_2
0,0,0,18,1,0,0,4,4,2,2,...,False,False,False,False,True,False,False,False,True,False
1,0,0,17,1,0,1,1,1,1,2,...,False,False,True,False,False,False,False,False,False,False
2,0,0,15,1,1,1,1,1,1,2,...,False,False,True,False,False,False,True,False,True,False
3,0,0,15,1,0,1,4,2,1,3,...,False,False,False,True,False,True,False,False,True,False
4,0,0,16,1,0,1,3,3,1,2,...,False,False,True,False,False,True,False,False,False,False
5,0,1,16,1,1,1,4,3,1,2,...,False,False,True,False,False,False,False,True,True,False
6,0,1,16,1,1,1,2,2,1,2,...,False,False,True,False,False,True,False,False,True,False
7,0,0,17,1,0,0,4,4,2,2,...,False,False,False,False,True,True,False,False,True,False
8,0,1,15,1,1,0,3,2,1,2,...,False,False,True,False,False,True,False,False,True,False
9,0,1,15,1,0,1,3,4,1,2,...,False,False,True,False,False,True,False,False,True,False

In [46]:
df_processado.head()

,age,Medu,Fedu,Mjob,Fjob,reason,guardian,traveltime,studytime,failures,...,famsize_LE3,Pstatus_T,schoolsup_yes,famsup_yes,paid_yes,activities_yes,nursery_yes,higher_yes,internet_yes,romantic_yes
0,18,4,4,at_home,teacher,course,mother,2,2,0,...,0,0,1,0,0,0,1,1,0,0
1,17,1,1,at_home,other,course,father,1,2,0,...,0,1,0,1,0,0,0,1,1,0
2,15,1,1,at_home,other,other,mother,1,2,3,...,1,1,1,0,1,0,1,1,1,0
3,15,4,2,health,services,home,mother,1,3,0,...,0,1,0,1,1,1,1,1,1,1
4,16,3,3,other,other,home,father,1,2,0,...,0,1,0,1,1,0,1,1,0,0